global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "aidg_rules.yml"

scrape_configs:
  - job_name: 'aidg_service'
    static_configs:
      - targets: ['aidg_service:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []